image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-python.python@2020.10.332292344:5ctthQ25Qni5/aAuOIUTYQ==
    - littlefoxteam.vscode-python-test-adapter@0.6.7:BjnXe8bR2Blf7wQHp264HQ==